name = "rta"
compatibility_date = "2025-02-05"

main = "./.cloudflare/worker.js"

site.bucket = "./.cloudflare/public"

build.command = "bun run build"

compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "rta"
database_id = "d54546be-6c7f-4dc1-88a3-8c740485ff57"
