name = "rta-cooked"
compatibility_date = "2025-02-06"

main = "./.cloudflare/worker.js"

site.bucket = "./.cloudflare/public"

build.command = "bun run build"

compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "DB"
database_name = "rta-cooked"
database_id = "70144cff-3caa-46b9-a2a4-5f291702da8d"
